### ISSUE TITLE
Bitbucket port

### ISSUE THREAD

**Issue by KatherineInCode** [dolmen/github-keygen#27]
How difficult would it be to port/update this script to handle Bitbucket? I have projects there as well as on Github, and it would be nice to have the same ease of key creation and security for there, too.

**Comment by dolmen** [comment]
I have no tuits to do that right now or in a near future.

The first major step required is to refactor github-keygen to separate a generic engine from plugins and make the GitHub specific parts as a plugin. Despites I have this idea for more than 5 years (see #2, #3, #8), I have not progressed on the matter because of the lack of motivation: not so many people are yet using github-keygen for the core GH features (in part because GitHub is nowadays pushing HTTPS more than SSH for connectivity) and almost nobody has shown interest in other platform support by commenting on the existing tickets.

**Comment by kdbertel** [comment]
That makes sense. Maybe things will change in the future, but I can live for now.
